# Generated by Django 5.0.3 on 2024-03-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('car_model', models.TextField(max_length=100)),
                ('car_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car_image', models.FileField(default=None, null=True, upload_to='images')),
                ('car_details', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
